name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: 
      - master

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      # Runs a single command using the runners shell
  ci:
    uses: bielu/bielu.GithubActions.Templates/.github/workflows/ci.yml@main
